apps/admin/views.py
# encoding:utf-8
from flask import Blueprint, render_template, request, session, redirect, url_for, make_response, jsonify
from io import BytesIO
from datetime import timedelta
from xpinyin import Pinyin
import config
from .models import Users
from .forms import LoginForm, ProductCatForm
from .decorators import login_require
from .utils import GetUser, BuildTree, BuildTable, BuildCatList
from apps.common.models import ProductCatagory
from utils.captcha import create_validate_code
from extends import db

bp = Blueprint("admin", __name__)


@bp.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        if session.get('image'):  # 回退未获取验证码……
            if session.get('image').lower() != form.captcha.data.lower():
                return render_template('admin/login.html', form=form, message='验证码错误！')
            user = Users.query.filter_by(username=form.username.data).first()
            if user and user.check_password(form.password.data):
                session[config.ADMIN_USER_ID] = user.uid
                if request.form.get('online'):  # 选择了记录登陆状态
                    session.permanent = True
                    bp.permanent_session_lifetime = timedelta(days=30)  # 有效期30天
                return redirect(url_for('admin.index'))
            else:
                return render_template('admin/login.html', form=form, message='用户名或密码错误！')
        else:
            return render_template('admin/login.html', form=form, message='验证码已失效！')
    else:
        return render_template('admin/login.html', form=form)


@bp.route('/logout/')
@login_require
def logout():
    del session[config.ADMIN_USER_ID]
    return redirect(url_for('admin.login'))


@bp.route('/code/')
def get_code():
    code_img, strs = create_validate_code()
    buf = BytesIO()
    code_img.save(buf, 'JPEG', quality=70)
    response = make_response(buf.getvalue())
    response.headers['Content-Type'] = 'image/jpeg'
    session['image'] = strs
    return response


@bp.route('/profile')
@login_require
def profile():
    return render_template('admin/profile.html', user=GetUser())


@bp.route('/checkpwd/')
@login_require
def checkpwd():
    oldpwd = request.args.get('oldpwd', '')
    user = GetUser()
    if user is not None and user.check_password(oldpwd):
        data = {
            "name": user.email,
            "status": 11
        }
    else:
        data = {
            'name': None,
            'status': 00
        }
    return jsonify(data)


@bp.route('/EditPassword', methods=['GET', 'POST'])
@login_require
def editpwd():
    if request.method == 'GET':
        return render_template('admin/edit_pwd.html')
    else:
        GetUser().password = request.form.get('newpwd1')
        db.session.commit()
        return render_template('admin/edit_pwd.html', message='密码修改成功!')


@bp.route('/AddProductCatagory', methods=['GET', 'POST'])
@login_require
def product_cat_add():
    if request.method == 'GET':
        categorys = ProductCatagory.query.all()
        ls = [{'sid': x.self_id, 'pid': x.parent_id, 'tname': x.type_name} for x in categorys]
        html = BuildTable(BuildTree(ls, 0, 0))
        return render_template('admin/product_cat_add.html', body=html)
    else:
        form = ProductCatForm(request.form)
        if form.validate():
            tname = request.form.get('type_name')
            dirpath = request.form.get('dirpath')
            check = request.form.get('check')
            if check or dirpath is None:
                dirpath = Pinyin().get_pinyin(tname, '')
            pid = request.form.get('parent_id')
            kws = request.form.get('keywords')
            des = request.form.get('description')
            psort = request.form.get('product_sort')
            vis = request.form.get('visable')
            insert = ProductCatagory(parent_id=pid, type_name=tname, keywords=kws, description=des, product_sort=psort,
                                     visable=vis, dirPath=dirpath)
            db.session.add(insert)
            db.session.commit()
            return redirect(url_for('admin.product_cat_list'))
        else:
            return "输入有误，校验未通过"


@bp.route('/ProductCatagoryList/', methods=['GET'])
@login_require
def product_cat_list():
    if request.method == 'GET':
        categorys = ProductCatagory.query.all()
        ls = [{'sid': x.self_id, 'pid': x.parent_id, 'tname': x.type_name, 'psort': x.product_sort,
               'description': x.description, 'dirpath': x.dirPath} for x in categorys]
        html = BuildCatList(BuildTree(ls, 0, 0))
        return render_template('admin/product_cat_list.html', body=html)


@bp.route('/EditProductCatagory/<id>/', methods=['GET', 'POST'])
@login_require
def product_cat_edit(id):
    if request.method == 'GET':
        current = ProductCatagory.query.filter_by(self_id=id).first()
        categorys = ProductCatagory.query.all()  # 取得所有分类
        ls = [{'sid': x.self_id, 'pid': x.parent_id, 'tname': x.type_name} for x in categorys]
        html = BuildTable(BuildTree(ls, 0, 0))
        return render_template('admin/product_cat_edit.html', content=current, body=html)
    else:
        form = ProductCatForm(request.form)
        if form.validate():
            tname = request.form.get('type_name')
            dirpath = request.form.get('dirpath')
            check = request.form.get('check')
            sid = int(request.form.get('self_id'))
            if check or dirpath is None:
                dirpath = Pinyin().get_pinyin(tname, '')
            pid = request.form.get('parent_id')
            kws = request.form.get('keywords')
            des = request.form.get('description')
            psort = request.form.get('product_sort')
            vis = request.form.get('visable')
            ProductCatagory.query.filter(ProductCatagory.self_id == sid).update(
                {ProductCatagory.parent_id: pid, ProductCatagory.type_name: tname, ProductCatagory.dirPath: dirpath,
                 ProductCatagory.keywords: kws, ProductCatagory.description: des,
                 ProductCatagory.product_sort: psort, ProductCatagory.visable: vis
                 })
            db.session.commit()
            return redirect(url_for('admin.product_cat_list'))


@bp.route('/DelProductCatagory/<id>', methods=['GET'])
@login_require
def product_cat_del(id):
    cat1 = ProductCatagory.query.filter(ProductCatagory.self_id == id).first()  # 查询出数据库中的记录
    db.session.delete(cat1)
    db.session.commit()
    return redirect(url_for('admin.product_cat_list'))


@bp.route('/welcome/')
@login_require
def welcome():
    return render_template('admin/welcome.html')


@bp.route('/')
@login_require
def index():
    return render_template('admin/index.html')


@bp.app_errorhandler(404)
def err_404(error):
    return render_template('ShowErr.html', ErrCode=404, ErrMsg='对不起，您要访问的资源不存在~')


@bp.app_errorhandler(500)
def err_404(error):
    return render_template('ShowErr.html', ErrCode=500, ErrMsg=error)


@bp.app_errorhandler(400)
def csrf_error(reason):
    return render_template('ShowErr.html', ErrCode=400, ErrMsg=reason)

templates/BaseFooter.html
<script type="text/javascript" src="{{url_for('static',filename='lib/jquery/1.9.1/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='lib/layer/3.1.1/layer.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='static/h-ui/js/H-ui.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='static/h-ui.admin/js/H-ui.admin.js')}}"></script>

templates/BaseHeader.html
<header class="navbar-wrapper">
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid cl">
			<span class="logo navbar-slogan f-l mr-10 hidden-xs">YJM-CMS</span>
			<a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
			<nav class="nav navbar-nav">
				<ul class="cl">
					<li class="dropDown dropDown_hover"><a href="javascript:;" class="dropDown_A"><i class="Hui-iconfont">&#xe600;</i> 新增 <i class="Hui-iconfont">&#xe6d5;</i></a>
						<ul class="dropDown-menu menu radius box-shadow">
							<li><a href="javascript:;" onclick="article_add('添加资讯','article-add.html')"><i class="Hui-iconfont">&#xe616;</i> 资讯</a></li>
							<li><a href="javascript:;" onclick="picture_add('添加资讯','picture-add.html')"><i class="Hui-iconfont">&#xe613;</i> 图片</a></li>
							<li><a href="javascript:;" onclick="product_add('添加资讯','product-add.html')"><i class="Hui-iconfont">&#xe620;</i> 产品</a></li>
							<li><a href="javascript:;" onclick="member_add('添加用户','member-add.html','','510')"><i class="Hui-iconfont">&#xe60d;</i> 用户</a></li>
                        </ul>
                        <li class="navbar-levelone current"><a href="javascript:;">平台</a></li>
                        <li class="navbar-levelone"><a href="javascript:;">商城</a></li>
                        <li class="navbar-levelone"><a href="javascript:;">财务</a></li>
                        <li class="navbar-levelone"><a href="javascript:;">手机</a></li>
                    </li>
                </ul>
            </nav>
            <nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
                <ul class="cl">
                    <li>管理员</li>
                    <li class="dropDown dropDown_hover">
                        <a href="#" class="dropDown_A">{{g.admin_user.username}} <i class="Hui-iconfont">&#xe6d5;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="{{url_for('admin.profile')}}">个人信息</a></li>
							<li><a href="{{url_for('admin.editpwd')}}">修改密码</a></li>
                            <li><a href="{{url_for('admin.login')}}">切换账户</a></li>
                            <li><a href="{{url_for('admin.logout')}}">退出</a></li>
                        </ul>
                    </li>
                    <li id="Hui-msg"> <a href="#" title="消息"><span class="badge badge-danger">999</span><i class="Hui-iconfont" style="font-size:18px">&#xe68a;</i></a> </li>
                    <li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
                            <li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
                            <li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
                            <li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
                            <li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
                            <li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

templates/BaseMenu.html
<aside class="Hui-aside">
	<div class="menu_dropdown bk_2">
		<dl id="menu-article">
			<dt><i class="Hui-iconfont">&#xe616;</i> 资讯管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="article-list.html" data-title="资讯管理" href="javascript:void(0)">资讯管理</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-picture">
			<dt><i class="Hui-iconfont">&#xe613;</i> 图片管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="picture-list.html" data-title="图片管理" href="javascript:void(0)">图片管理</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-product">
			<dt><i class="Hui-iconfont">&#xe620;</i> 产品管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="product-brand.html" data-title="品牌管理" href="javascript:void(0)">品牌管理</a></li>
					<li><a data-href="{{url_for('admin.product_cat_list')}}" data-title="分类管理" href="javascript:void(0)">分类管理</a></li>
					<li><a data-href="product-list.html" data-title="产品管理" href="javascript:void(0)">产品管理</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-comments">
			<dt><i class="Hui-iconfont">&#xe622;</i> 评论管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="http://h-ui.duoshuo.com/admin/" data-title="评论列表" href="javascript:;">评论列表</a></li>
					<li><a data-href="feedback-list.html" data-title="意见反馈" href="javascript:void(0)">意见反馈</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-member">
			<dt><i class="Hui-iconfont">&#xe60d;</i> 会员管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="member-list.html" data-title="会员列表" href="javascript:;">会员列表</a></li>
					<li><a data-href="member-del.html" data-title="删除的会员" href="javascript:;">删除的会员</a></li>
					<li><a data-href="member-level.html" data-title="等级管理" href="javascript:;">等级管理</a></li>
					<li><a data-href="member-scoreoperation.html" data-title="积分管理" href="javascript:;">积分管理</a></li>
					<li><a data-href="member-record-browse.html" data-title="浏览记录" href="javascript:void(0)">浏览记录</a></li>
					<li><a data-href="member-record-download.html" data-title="下载记录" href="javascript:void(0)">下载记录</a></li>
					<li><a data-href="member-record-share.html" data-title="分享记录" href="javascript:void(0)">分享记录</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-admin">
			<dt><i class="Hui-iconfont">&#xe62d;</i> 管理员管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="admin-role.html" data-title="角色管理" href="javascript:void(0)">角色管理</a></li>
					<li><a data-href="admin-permission.html" data-title="权限管理" href="javascript:void(0)">权限管理</a></li>
					<li><a data-href="admin-list.html" data-title="管理员列表" href="javascript:void(0)">管理员列表</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-tongji">
			<dt><i class="Hui-iconfont">&#xe61a;</i> 系统统计<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="charts-1.html" data-title="折线图" href="javascript:void(0)">折线图</a></li>
					<li><a data-href="charts-2.html" data-title="时间轴折线图" href="javascript:void(0)">时间轴折线图</a></li>
					<li><a data-href="charts-3.html" data-title="区域图" href="javascript:void(0)">区域图</a></li>
					<li><a data-href="charts-4.html" data-title="柱状图" href="javascript:void(0)">柱状图</a></li>
					<li><a data-href="charts-5.html" data-title="饼状图" href="javascript:void(0)">饼状图</a></li>
					<li><a data-href="charts-6.html" data-title="3D柱状图" href="javascript:void(0)">3D柱状图</a></li>
					<li><a data-href="charts-7.html" data-title="3D饼状图" href="javascript:void(0)">3D饼状图</a></li>
				</ul>
			</dd>
		</dl>
		<dl id="menu-system">
			<dt><i class="Hui-iconfont">&#xe62e;</i> 系统管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="system-base.html" data-title="系统设置" href="javascript:void(0)">系统设置</a></li>
					<li><a data-href="system-category.html" data-title="栏目管理" href="javascript:void(0)">栏目管理</a></li>
					<li><a data-href="system-data.html" data-title="数据字典" href="javascript:void(0)">数据字典</a></li>
					<li><a data-href="system-shielding.html" data-title="屏蔽词" href="javascript:void(0)">屏蔽词</a></li>
					<li><a data-href="system-log.html" data-title="系统日志" href="javascript:void(0)">系统日志</a></li>
				</ul>
			</dd>
		</dl>
	</div>

	<div class="menu_dropdown bk_2" style="display:none">
		<dl id="menu-aaaaa">
			<dt><i class="Hui-iconfont">&#xe616;</i> 二级导航1<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="article-list.html" data-title="资讯管理" href="javascript:void(0)">三级导航</a></li>
				</ul>
			</dd>
		</dl>
	</div>

	<div class="menu_dropdown bk_2" style="display:none">
		<dl id="menu-bbbbb">
			<dt><i class="Hui-iconfont">&#xe616;</i> 二级导航2<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="article-list.html" data-title="资讯管理" href="javascript:void(0)">三级导航</a></li>
				</ul>
			</dd>
		</dl>
	</div>

	<div class="menu_dropdown bk_2" style="display:none">
		<dl id="menu-ccccc">
			<dt><i class="Hui-iconfont">&#xe616;</i> 二级导航3<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="article-list.html" data-title="资讯管理" href="javascript:void(0)">三级导航</a></li>
				</ul>
			</dd>
		</dl>
	</div>

</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>

templates/BaseMeta.html
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="Bookmark" href="/favicon.ico" >
<link rel="Shortcut Icon" href="/favicon.ico" />
<!--[if lt IE 9]>
<script type="text/javascript" src="{{url_for('static',filename='lib/html5shiv.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='lib/respond.min.js')}}"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='static/h-ui/css/H-ui.min.css')}}" />
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='static/h-ui.admin/css/H-ui.admin.css')}}" />
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='lib/Hui-iconfont/1.0.8/iconfont.css')}}" />
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='static/h-ui.admin/skin/green/skin.css')}}" id="skin" />
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='static/h-ui.admin/css/style.css')}}" />
<!--[if IE 6]>
<script type="text/javascript" src="{{url_for('static',filename='lib/DD_belatedPNG_0.0.8a-min.js')}}" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->

templates/BootStrapBase.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{{url_for('static',filename='/lib/layer/3.1.1/layer.js')}}"></script>

templates/ShowErr.html
<!DOCTYPE HTML>
<html>

<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport"
		content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
	<meta http-equiv="Cache-Control" content="no-siteapp" />
	<!--[if lt IE 9]>
<script type="text/javascript" src="{{url_for('static',filename='lib/html5shiv.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='lib/respond.min.js')}}"></script>
<![endif]-->
	<link href="{{url_for('static',filename='lib/Hui-iconfont/1.0.8/iconfont.css')}}" rel="stylesheet"
		type="text/css" />
	<link href="{{url_for('static',filename='static/h-ui/css/H-ui.min.css')}}" rel="stylesheet" type="text/css" />
	<link href="{{url_for('static',filename='static/h-ui.admin/css/H-ui.admin.css')}}" rel="stylesheet"
		type="text/css" />
	<!--[if IE 6]>
<script type="text/javascript" src="{{url_for('static',filename='lib/DD_belatedPNG_0.0.8a-min.js')}}" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
	<title>错误提示页面</title>
</head>

<body>
	<section class="container-fluid page-404 minWP text-c">
		<p class="error-title"><i class="Hui-iconfont va-m" style="font-size:80px">&#xe688;</i>
			<span class="va-m"> {% if ErrCode%}{{ErrCode}}{% else %}404{%endif%}</span>
		</p>
		<p class="error-description">{% if ErrMsg %}{{ErrMsg}}{% else %}不好意思，您访问的页面不存在~{%endif%}</p>
		<p class="error-info">您可以：
			<a href="javascript:;" onclick="history.go(-1)" class="c-primary">&lt; 返回上一页</a>
			<span class="ml-20">|</span>
			<a href="/" class="c-primary ml-20">去首页 &gt;</a>
		</p>
	</section>
</body>

</html>

templates/_blank.html
<!DOCTYPE HTML>
<html>

<head>
  <meta charset="utf-8">
  <meta name="renderer" content="webkit|ie-comp|ie-stand">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport"
    content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="Bookmark" href="/favicon.ico">
  <link rel="Shortcut Icon" href="/favicon.ico" />
  <!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>

<![endif]-->
  <link href="static/h-ui/css/H-ui.min.css" rel="stylesheet" type="text/css" />
  <link href="static/h-ui.admin/css/H-ui.admin.css" rel="stylesheet" type="text/css" />
  <link href="lib/Hui-iconfont/1.0.8/iconfont.css" rel="stylesheet" type="text/css" />

  <!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
  <title>空白页</title>
</head>

<body>
  <div class="pd-20">
    这是一个空白页
  </div>
  <script type="text/javascript" src="lib/jquery/1.9.1/jquery.min.js"></script>
  <script type="text/javascript" src="lib/layer/3.1.1/layer.js"></script>
  <script type="text/javascript" src="lib/jquery.validation/1.14.0/jquery.validate.js"></script>
  <script type="text/javascript" src="lib/jquery.validation/1.14.0/validate-methods.js"></script>
  <script type="text/javascript" src="lib/jquery.validation/1.14.0/messages_zh.js"></script>
  <script type="text/javascript" src="static/h-ui/js/H-ui.min.js"></script>
  <script type="text/javascript" src="static/h-ui.admin/js/H-ui.admin.js"></script>
</body>

</html>